from app.data_oracle.db_schema.utils import translate_sql_args

big_translation_map = {'public': {'name': 'public', 'Tables': {'usermodel': {'name': 'UserModel',
                                                                             'Columns': {'id': 'id',
                                                                                         'createdat': 'createdAt',
                                                                                         'email': 'email',
                                                                                         'username': 'username',
                                                                                         'first_name': 'first_name',
                                                                                         'last_name': 'last_name',
                                                                                         'phone_number': 'phone_number',
                                                                                         'credits': 'credits',
                                                                                         'spent': 'spent',
                                                                                         'opt_out_data': 'opt_out_data'}},
                                                               'visualizationcommand': {'name': 'VisualizationCommand',
                                                                                        'Columns': {'id': 'id',
                                                                                                    'createdat': 'createdAt',
                                                                                                    'create_command': 'create_command',
                                                                                                    'visid': 'visId',
                                                                                                    'userid': 'userId'}},
                                                               'tablecommand': {'name': 'TableCommand',
                                                                                'Columns': {'id': 'id',
                                                                                            'createdat': 'createdAt',
                                                                                            'create_command': 'create_command',
                                                                                            'tableid': 'tableId',
                                                                                            'userid': 'userId'}},
                                                               'reportcommand': {'name': 'ReportCommand',
                                                                                 'Columns': {'id': 'id',
                                                                                             'createdat': 'createdAt',
                                                                                             'create_command': 'create_command',
                                                                                             'report_id': 'report_id',
                                                                                             'userid': 'userId'}},
                                                               'subscription': {'name': 'Subscription',
                                                                                'Columns': {'id': 'id',
                                                                                            'createdat': 'createdAt',
                                                                                            'userid': 'userId',
                                                                                            'apilimit': 'apiLimit',
                                                                                            'stripe_customer_id': 'stripe_customer_id',
                                                                                            'stripe_subscription_id': 'stripe_subscription_id',
                                                                                            'stripe_price_id': 'stripe_price_id',
                                                                                            'stripe_current_period_end': 'stripe_current_period_end',
                                                                                            'stripe_current_period_start': 'stripe_current_period_start',
                                                                                            'cancelatperiodend': 'cancelAtPeriodEnd'}},
                                                               'files': {'name': 'Files', 'Columns': {'id': 'id',
                                                                                                      'createdat': 'createdAt',
                                                                                                      'filename': 'filename',
                                                                                                      'url': 'url',
                                                                                                      'preview': 'preview',
                                                                                                      'usermodelid': 'userModelId'}},
                                                               'apitransaction': {'name': 'ApiTransaction',
                                                                                  'Columns': {'id': 'id',
                                                                                              'createdat': 'createdAt',
                                                                                              'costs': 'costs',
                                                                                              'vis_command_id': 'vis_command_id',
                                                                                              'reportcommandid': 'reportCommandId',
                                                                                              'chatmessageid': 'chatMessageId',
                                                                                              'usermodelid': 'userModelId',
                                                                                              'table_command_id': 'table_command_id',
                                                                                              'erlang_id': 'erlang_id'}},
                                                               'chat': {'name': 'Chat',
                                                                        'Columns': {'id': 'id', 'title': 'title',
                                                                                    'createdat': 'createdAt',
                                                                                    'usermodelid': 'userModelId',
                                                                                    'isactive': 'isActive',
                                                                                    'excelid': 'excelId',
                                                                                    'dbid': 'dbId',
                                                                                    'chattype': 'chatType'}},
                                                               'chatmessage': {'name': 'ChatMessage',
                                                                               'Columns': {'id': 'id',
                                                                                           'createdat': 'createdAt',
                                                                                           'message': 'message',
                                                                                           'translated_message': 'translated_message',
                                                                                           'sql': 'sql',
                                                                                           'is_error': 'is_error',
                                                                                           'role': 'role',
                                                                                           'chatid': 'chatId',
                                                                                           'score': 'score'}},
                                                               'dashboard': {'name': 'Dashboard',
                                                                             'Columns': {'id': 'id',
                                                                                         'createdat': 'createdAt',
                                                                                         'layout': 'layout',
                                                                                         'content': 'content',
                                                                                         'logo_path': 'logo_path',
                                                                                         'title': 'title',
                                                                                         'company': 'company',
                                                                                         'usermodelid': 'userModelId',
                                                                                         'updatedat': 'updatedAt',
                                                                                         'preview': 'preview'}},
                                                               'visualization': {'name': 'Visualization',
                                                                                 'Columns': {'id': 'id',
                                                                                             'createdat': 'createdAt',
                                                                                             'sql': 'sql',
                                                                                             'config': 'config',
                                                                                             'message_id': 'message_id',
                                                                                             'bookmark': 'bookmark',
                                                                                             'excelid': 'excelId',
                                                                                             'dbid': 'dbId',
                                                                                             'userid': 'userId',
                                                                                             'code': 'code',
                                                                                             'erlang_id': 'erlang_id'}},
                                                               'databaseconnection': {'name': 'DatabaseConnection',
                                                                                      'Columns': {'id': 'id',
                                                                                                  'createdat': 'createdAt',
                                                                                                  'description': 'description',
                                                                                                  'name': 'name',
                                                                                                  'type': 'type',
                                                                                                  'host': 'host',
                                                                                                  'port': 'port',
                                                                                                  'user_name': 'user_name',
                                                                                                  'password_secret': 'password_secret',
                                                                                                  'db_schema': 'db_schema',
                                                                                                  'synchronize': 'synchronize',
                                                                                                  'synchronizedat': 'synchronizedAt',
                                                                                                  'bq_project_id': 'bq_project_id',
                                                                                                  'bq_key_file': 'bq_key_file',
                                                                                                  'ssh_ip': 'ssh_ip',
                                                                                                  'ssh_port': 'ssh_port',
                                                                                                  'ssh_remote_ip': 'ssh_remote_ip',
                                                                                                  'ssh_remote_port': 'ssh_remote_port',
                                                                                                  'ssh_user': 'ssh_user',
                                                                                                  'ssh_password_secret': 'ssh_password_secret',
                                                                                                  'ssh_private_key': 'ssh_private_key',
                                                                                                  'ssh_key_type': 'ssh_key_type',
                                                                                                  'usermodelid': 'userModelId'}},
                                                               'excelfile': {'name': 'ExcelFile',
                                                                             'Columns': {'id': 'id', 'name': 'name',
                                                                                         'filepath': 'filepath',
                                                                                         'createdat': 'createdAt',
                                                                                         'description': 'description',
                                                                                         'usermodelid': 'userModelId',
                                                                                         'db_schema': 'db_schema',
                                                                                         'synchronizedat': 'synchronizedAt'}},
                                                               'apiconnection': {'name': 'ApiConnection',
                                                                                 'Columns': {'id': 'id',
                                                                                             'createdat': 'createdAt',
                                                                                             'apitype': 'apitype',
                                                                                             'config': 'config',
                                                                                             'usermodelid': 'userModelId'}},
                                                               'datatable': {'name': 'DataTable',
                                                                             'Columns': {'id': 'id',
                                                                                         'createdat': 'createdAt',
                                                                                         'sql': 'sql',
                                                                                         'message_id': 'message_id',
                                                                                         'title': 'title',
                                                                                         'subtitle': 'subtitle',
                                                                                         'divider': 'divider',
                                                                                         'bookmark': 'bookmark',
                                                                                         'excelid': 'excelId',
                                                                                         'dbid': 'dbId',
                                                                                         'userid': 'userId',
                                                                                         'code': 'code',
                                                                                         'erlang_id': 'erlang_id'}},
                                                               'textfile': {'name': 'TextFile',
                                                                            'Columns': {'id': 'id', 'name': 'name',
                                                                                        'createdat': 'createdAt',
                                                                                        'description': 'description',
                                                                                        'content': 'content',
                                                                                        'usermodelid': 'userModelId'}},
                                                               'report': {'name': 'Report', 'Columns': {'id': 'id',
                                                                                                        'createdat': 'createdAt',
                                                                                                        'layout': 'layout',
                                                                                                        'config': 'config',
                                                                                                        'preview': 'preview',
                                                                                                        'title': 'title',
                                                                                                        'usermodelid': 'userModelId',
                                                                                                        'updatedat': 'updatedAt'}},
                                                               'dbschematraining': {'name': 'DbSchemaTraining',
                                                                                    'Columns': {'id': 'id',
                                                                                                'createdat': 'createdAt',
                                                                                                'db_schema': 'db_schema',
                                                                                                'db_id': 'db_id',
                                                                                                'excel_id': 'excel_id',
                                                                                                'usermodelid': 'userModelId'}},
                                                               '_apiconnectiontochat': {'name': '_ApiConnectionToChat',
                                                                                        'Columns': {'a': 'A',
                                                                                                    'b': 'B'}},
                                                               '_apiconnectiontovisualization': {
                                                                   'name': '_ApiConnectionToVisualization',
                                                                   'Columns': {'a': 'A', 'b': 'B'}},
                                                               '_apiconnectiontodatatable': {
                                                                   'name': '_ApiConnectionToDataTable',
                                                                   'Columns': {'a': 'A', 'b': 'B'}},
                                                               '_vieweruser': {'name': '_ViewerUser',
                                                                               'Columns': {'a': 'A', 'b': 'B'}},
                                                               'trainingexamples': {'name': 'TrainingExamples',
                                                                                    'Columns': {'id': 'id',
                                                                                                'createdat': 'createdAt',
                                                                                                'question': 'question',
                                                                                                'sql': 'sql',
                                                                                                'dbschema_id': 'dbschema_id',
                                                                                                'chat_msg_id': 'chat_msg_id',
                                                                                                'type': 'type',
                                                                                                'chatmessageerlangid': 'chatMessageErlangId'}},
                                                               'chatmessageerlang': {'name': 'ChatMessageErlang',
                                                                                     'Columns': {'id': 'id',
                                                                                                 'createdat': 'createdAt',
                                                                                                 'message': 'message',
                                                                                                 'translated_message': 'translated_message',
                                                                                                 'action_sequence': 'action_sequence',
                                                                                                 'is_error': 'is_error',
                                                                                                 'role': 'role',
                                                                                                 'chatid': 'chatId',
                                                                                                 'score': 'score'}}}}}


def test_without_schemas():
    translationmap = {'public': {'name': 'public', 'Tables': {
        'employee_sample_data': {'name': 'Employee_Sample_data', 'Columns': {'index': 'index', 'eeid': 'eeid',
                                                                             'full_name': 'full_name',
                                                                             'job_title': 'job_title',
                                                                             'department': 'department',
                                                                             'business_unit': 'business_unit',
                                                                             'gender': 'gender',
                                                                             'ethnicity': 'ethnicity',
                                                                             'age': 'age', 'hire_date': 'hire_date',
                                                                             'annual_salary': 'annual_salary',
                                                                             'bonus_': 'bonus_', 'country': 'country',
                                                                             'city': 'city',
                                                                             'exit_date': 'exit_date'}}}}}

    sql_query = """SELECT department, AVG(CAST(REPLACE(REPLACE(annual_salary, ',', ''), '$', '') AS DECIMAL)) AS avg_annual_salary
    FROM employee_sample_data GROUP BY department"""
    assert translate_sql_args(sql_query, translationmap,
                              "PostgreSQL") == '''SELECT "Employee_Sample_data"."department" AS "department", AVG(CAST(REPLACE(REPLACE("Employee_Sample_data"."annual_salary", ',', ''), '$', '') AS DECIMAL)) AS "avg_annual_salary" FROM "Employee_Sample_data" AS "Employee_Sample_data" GROUP BY "Employee_Sample_data"."department"'''


def test_with_schemas():
    sql_query_complex1 = """SELECT u.id, u.username, u.email, u.createdat, (
        SELECT COUNT(*) 
        FROM public.apitransaction a 
        WHERE a.usermodelid = u.id
    ) as api_transaction_count
    FROM public.usermodel u
    WHERE u.id IN (
        SELECT DISTINCT usermodelid 
        FROM public.apitransaction
    )
    ORDER BY api_transaction_count DESC;"""

    assert translate_sql_args(sql_query_complex1, big_translation_map,
                              "PostgreSQL") == '''WITH "_u_0" AS (SELECT COUNT(*) AS "_col_0", "a"."userModelId" AS "_u_1" FROM "public"."ApiTransaction" AS "a" GROUP BY "a"."userModelId"), "_u_2" AS (SELECT DISTINCT "ApiTransaction"."userModelId" AS "usermodelid" FROM "public"."ApiTransaction" AS "ApiTransaction" GROUP BY "ApiTransaction"."userModelId") SELECT "u"."id" AS "id", "u"."username" AS "username", "u"."email" AS "email", "u"."createdAt" AS "createdat", COALESCE("_u_0"."_col_0", 0) AS "api_transaction_count" FROM "public"."UserModel" AS "u" LEFT JOIN "_u_0" AS "_u_0" ON "_u_0"."_u_1" = "u"."id" LEFT JOIN "_u_2" AS "_u_2" ON "_u_2"."usermodelid" = "u"."id" WHERE NOT "_u_2"."usermodelid" IS NULL ORDER BY "api_transaction_count" DESC'''


def test_with_schemas2():
    sql_query_complex2 = """SELECT *
        FROM (
          SELECT *
          FROM public.chatmessage
          WHERE is_error = FALSE
        ) AS active_chat_messages
        JOIN public.chat
        ON active_chat_messages.chatid = chat.id
        JOIN public.usermodel
        ON chat.usermodelid = usermodel.id;
        """

    assert translate_sql_args(sql_query_complex2, big_translation_map,
                              "PostgreSQL") == '''WITH "active_chat_messages" AS (SELECT * FROM "public"."ChatMessage" AS "ChatMessage" WHERE "ChatMessage"."is_error" = FALSE) SELECT * FROM "active_chat_messages" AS "active_chat_messages" JOIN "public"."Chat" AS "Chat" ON "active_chat_messages"."chatId" = "Chat"."id" JOIN "public"."UserModel" AS "UserModel" ON "Chat"."userModelId" = "UserModel"."id"'''
